services:
  mysql:
    image: mysql:8.0
    container_name: app_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'mysqladmin ping -h 127.0.0.1 -uroot -p$${MYSQL_ROOT_PASSWORD} || exit 1',
        ]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 60s
  phpmyadmin:
    image: phpmyadmin:latest
    platform: linux/arm64
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      UPLOAD_LIMIT: 64M
    ports:
      - '8080:80'
    depends_on:
      - mysql

  backend:
    build:
      context: ./BE_PHONGDAOTAO
      dockerfile: Dockerfile
    image: ghcr.io/mnhwuanz/demo_phongdaotao-backend:latest
    container_name: app_backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql:3306/${MYSQL_DATABASE}
      SYSTEM_URL: ${SYSTEM_URL}
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build:
      context: ./FE_PHONGDAOTAO
      dockerfile: Dockerfile
    image: ghcr.io/mnhwuanz/demo_phongdaotao-frontend:latest
    container_name: app_frontend
    restart: unless-stopped
    depends_on:
      - backend

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: app_cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN}
    depends_on:
      - frontend
    networks:
      - default
      - proxy

volumes:
  mysql_data:

networks:
  proxy:
    external: true
